apiVersion : v2
name       : UNIVERSAL 
description: Easy configure deployment
type       : application
version    : 0.0.0
appVersion : "0.0.0"

maintainers:
  - name : "Roman Bykov"
    email: all@h963z57.com
  - name : "Andrei Perepechaev"

dependencies:
  # DISABLED
  # - name: Secman-config
  #   version: 0.0.0
  #   repository: "file://../libraries/secman"
  - name: Deployment-config
    version: 0.0.0
    repository: "file://../libraries/deployment"