
# ==================================================================================================================================================
# {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{ >EDIT PARAMETERS< }}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
# ==================================================================================================================================================

IMAGES:

  
# ==================================================================================================================================================
# {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{[[{ >DEFAULT PARAMETERS< }]]}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
# ==================================================================================================================================================

COMMANDS:
  default_EXAMPLE:
  #   - "/bin/sh"
  #   - "..."

ARGS:
  default_EXAMPLE:
  #   - "-c"
  #   - "-b"
    
ENVIRONMENTS:
  default_EXAMPLE:
  #   - {name: EXAMPLE, type: fieldRef, value: val  }
  #   - {name: EXAMPLE, type: text,     value: val  }
  #   - {name: EXAMPLE, type: fieldRef, value: val  }
  #   - {name: EXAMPLE, type: text,     value: "val"}

VOLUME_MOUNTS:
  default_EXAMPLE:
  #   - {name: example, mountPath: /destination/path, fieldRef: ["metadata.labels", "metadata.annotations"]                    }
  #   - {name: example, mountPath: /destination/path, serviceAccountToken: '{<body>}'                                          }
  #   - {name: example, mountPath: /destination/path, subPath: root-cert.pem, configMapName: existConfigMapName, noPrefix: true}
  #   - {name: example, mountPath: /destination/path, emptyDir: regular                                                        }
    # - {name: example, mountPath: /destination/path, emptyDir: memory                                                         }



PROBES:
  default_DJANGO: 
    readinessProbe: '{failureThreshold: 3, initialDelaySeconds: 60, periodSeconds: 30, successThreshold: 1, tcpSocket: {port: 8000}, timeoutSeconds: 10}'
    livenessProbe : '{failureThreshold: 3, initialDelaySeconds: 60, periodSeconds: 30, successThreshold: 1, tcpSocket: {port: 8000}, timeoutSeconds: 10}'
  default_PHP: 
    readinessProbe: '{exec: {command: ["/bin/sh", "-c", "curl -f http://localhost:80/ || exit 1"]}, failureThreshold: 3, initialDelaySeconds: 60, periodSeconds: 30, successThreshold: 1, timeoutSeconds: 10}'
    livenessProbe:  '{exec: {command: ["/bin/sh", "-c", "curl -f http://localhost:80/ || exit 1"]}, failureThreshold: 3, initialDelaySeconds: 60, periodSeconds: 30, successThreshold: 1, timeoutSeconds: 10}'
  default_GRAFANA:
    livenessProbe : '{httpGet: {path: /api/health, port: 3000}, initialDelaySeconds: 30, timeoutSeconds: 5, periodSeconds: 10, failureThreshold: 3}'
    readinessProbe: '{httpGet: {path: /api/health, port: 3000}, initialDelaySeconds: 10, timeoutSeconds: 5, periodSeconds: 10, failureThreshold: 3}'
  default_PROMETHEUS:
    livenessProbe : '{httpGet: {path: /-/healthy, port: 9090}, initialDelaySeconds: 30, timeoutSeconds: 5, periodSeconds: 10, failureThreshold: 3}'
    readinessProbe: '{httpGet: {path: /-/ready,   port: 9090}, initialDelaySeconds: 10, timeoutSeconds: 5, periodSeconds: 10, failureThreshold: 3}'
  default_REDIS:
    readinessProbe: '{failureThreshold: 3, initialDelaySeconds: 60, periodSeconds: 30, successThreshold: 1, tcpSocket: {port: 6379}, timeoutSeconds: 10}'
    livenessProbe : '{failureThreshold: 3, initialDelaySeconds: 60, periodSeconds: 30, successThreshold: 1, tcpSocket: {port: 6379}, timeoutSeconds: 10}'

PORTS:
  default_DJANGO:
    - {name: http,       port: 8000,  protocol: TCP}
  default_PHP:
    - {name: http,       port: 80,    protocol: TCP}
  default_GRAFANA:
    - {name: http,       port: 3000,  protocol: TCP}
  default_PROMETHEUS:
    - {name: prometheus, port: 9090,  protocol: TCP}
  default_REDIS:
    - {name: redis,      port: 6379,  protocol: TCP}

RESOURCES:
  default_EXAMPLE:
  # DJANGO: { CPU_REQUESTS: "100m", CPU_LIMIT: "500m", RAM_REQUESTS: "100Mi", RAM_LIMIT: "200Mi" }
  # PHP   : { CPU_REQUESTS: "50m",  CPU_LIMIT: "200m", RAM_REQUESTS: "100Mi", RAM_LIMIT: "200Mi" }

# DCM:
#   default_EXAMPLE:
#     - name: config-file
#       mountPath: /app/il/tmp/conf
#       configMapName: tomcat-cm
#       subPath: web.xml
#       content:
#       - data: |-
#           <body>

DCM:
  default_PROMETHEUS:
    - name: prometheus
      mountPath: /etc/prometheus
      configMapName: prometheus-config
      subPath: prometheus.yml
      content:
      - data: |-
          global:
            scrape_interval: 15s
          scrape_configs:
            {{- range $index, $value := $.Values.CONFIGMAPS.PROMETHEUS.HOSTS }}
            - job_name: '{{ $value.jobName }}'
              scrape_interval: 5s
              static_configs:
                {{- range $targetIndex, $target := $value.targets }}
                - targets: ['{{ $target.url }}']
                  labels:
                    instance: "{{ $target.labels }}"
                {{- end }}
            {{- end }}

# GRACEFULL_SHUTDOWN:
#   ASBS:
#     - {name: lifecycle,  httpGet: {path: /il/sys/shutdown.jsps, port: 9080, scheme: HTTP}}

# ==================================================================================================================================================
# {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{[{ >STATIC PARAMETERS< }}]}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
# ==================================================================================================================================================

ENVIRONMENT: prod

REPLICAS: "1"

IMAGE_PATHS:
  prod: docker.io

SECURITYCONTEXT:
  default: |-
    capabilities: 
      drop:
        - ALL
    # privileged: false
    # runAsNonRoot: true
    # readOnlyRootFilesystem: true
    # allowPrivilegeEscalation: false