apiVersion: v2
appVersion: 0.0.0
description: A library for secman
maintainers:
- name : "Roman Bykov"
  email: all@h963z57.com
- name : "Andrei Perepechaev"
name: Secman-config
type: library
version: 0.0.0
