{{- define "resources.limits" -}}
{{- if .Values.RESOURCES }}
# ========== LIMITS =============
resources:
  {{- if .Values.RESOURCES.LIMIT }}
  limits:
    {{- if .Values.RESOURCES.LIMIT.CPU }}
    cpu: "{{ .Values.RESOURCES.LIMIT.CPU }}" 
    {{- end }} 
    {{- if .Values.RESOURCES.LIMIT.MEMORY }}
    memory: "{{ .Values.RESOURCES.LIMIT.MEMORY }}" 
    {{- end }}
  {{- end }}
  {{- if .Values.RESOURCES.REQUESTS }}
  requests:
    {{- if .Values.RESOURCES.REQUESTS.CPU }}
    cpu: "{{ .Values.RESOURCES.REQUESTS.CPU }}" 
    {{- end }} 
    {{- if .Values.RESOURCES.REQUESTS.MEMORY }}
    memory: "{{ .Values.RESOURCES.REQUESTS.MEMORY }}" 
    {{- end }}
  {{- end }}
{{- end }}
{{- end -}}