{{- define "resources.priority" -}}
{{- if $.Values.PRIORITY }}
# ========== PRIORITY ===========
priorityClassName: {{ $.Values.PROJECT_NAME }}-pc
affinity:
  nodeAffinity:
    {{- if  $.Values.PRIORITY.STRICT }}
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
    {{- else }}
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
    {{- end }}
            {{- range $.Values.PRIORITY.NODE_SELECTOR }}
            - key: {{ .label }}
              operator: In
              values:
                - "{{ .value }}"
            {{- end }}
{{- end }}
{{- end -}}