{{- define "secman.config" -}}
# --== Lib deploy SECMAN config ==--
{{- $env := .Values.ENVIRONMENT }}
{{- $role := default .Release.Namespace (( index $.Values.SECMAN_CONFIG $env $.Values.CLUSTER).ROLE ) }}
{{- if eq $.Values.SECMAN_CONFIG.SECMANMODE "initial" }}
# == Setup mode INITIAL ==
vault.hashicorp.com/agent-inject: 'true'
vault.hashicorp.com/namespace: {{ index $.Values.SECMAN_NAMESPACE $env }}
vault.hashicorp.com/role: {{ $role }}
vault.hashicorp.com/agent-pre-populate-only: 'true'
vault.hashicorp.com/agent-init-first: 'false'
vault.hashicorp.com/agent-pre-populate: 'true'
{{- else if eq $.Values.SECMAN_CONFIG.SECMANMODE "agent" }}
# == Setup mode  AGENT ==
vault.hashicorp.com/agent-pre-populate: "false"
# vault.hashicorp.com/log-level: debug
vault.hashicorp.com/agent-init-first: "false"
vault.hashicorp.com/agent-inject: "true"
vault.hashicorp.com/agent-inject-default-template: json
vault.hashicorp.com/namespace: {{ index $.Values.SECMAN_NAMESPACE $env }}
vault.hashicorp.com/role: {{ $role }}
{{- else }}
vault.hashicorp.com/agent-pre-populate: 'false'
{{- end }}
vault.hashicorp.com/agent-service-account-token-volume-name: vault-agent-token-volume
{{- if $.Values.RESOURCES.VAULT }}
vault.hashicorp.com/agent-requests-mem: {{ default "64Mi" ( tpl $.Values.RESOURCES.VAULT.RAM_REQUESTS $ ) }}
vault.hashicorp.com/agent-requests-cpu: {{ default "250m" ( tpl $.Values.RESOURCES.VAULT.CPU_REQUESTS $ ) }}
vault.hashicorp.com/agent-limits-mem: {{ default "128Mi" ( tpl $.Values.RESOURCES.VAULT.RAM_LIMIT $ ) }}
vault.hashicorp.com/agent-limits-cpu: {{ default "500m" ( tpl $.Values.RESOURCES.VAULT.CPU_LIMIT $ ) }}
{{- end }}
{{- end -}}