{{- define "secman.secrets" -}}
{{- $Global := .Global }}
{{- if $Global.Values.SECMAN_SECRETS }}
# --== Lib deploy SECMAN secrets ==--
{{- $env := $Global.Values.ENVIRONMENT }}
{{- range $listIndex , $array := (list 
  (index $Global.Values.SECMAN_SECRETS (printf "default_%s" (upper .presetLabel))) 
  (index $Global.Values.SECMAN_SECRETS (upper .presetLabel))
  (index $Global.Values.SECMAN_SECRETS $env)
)}}
{{- range $index, $value := $array }}
{{- /* --==================== First cycle ====================-- */}}
vault.hashicorp.com/agent-inject-secret-{{ $value.mountName }}-{{ $listIndex }}-{{ $index }}: 'true'
vault.hashicorp.com/agent-inject-file-{{ $value.mountName }}-{{ $listIndex }}-{{ $index }}: {{ $value.mountName }}
vault.hashicorp.com/secret-volume-path-{{ $value.mountName }}-{{ $listIndex }}-{{ $index }}: {{ $value.mountPath }}
{{- /* --== Определяем права доступа к финальным файлам в поде, по необходимости ==-- */}}
{{- if $value.permissions }}
vault.hashicorp.com/agent-inject-perms-{{ $value.mountName }}-{{ $listIndex }}-{{ $index }}: '{{ $value.permissions }}'
{{- end }}
# ^^^^^^^^^^^^^^^^^ Secret config {{ $value.mountName }} ^^^^^^^^^^^^^^^^^^
vault.hashicorp.com/agent-inject-template-{{ $value.mountName }}-{{ $listIndex }}-{{ $index }}: >
{{- /* 

--==================== Second cycle ====================-- 

*/}}
{{- range $count, $secret := $value.secrets }}
{{- /* --== Обозначаем параметры по-умолчанию для SBERCA client ==-- */}}
{{- $kvPath     := default (printf "%s/%s" (index $Global.Values.SECMAN_PATH $env) $Global.Release.Namespace) (( index $Global.Values.SECMAN_CONFIG $env $Global.Values.CLUSTER ).PATH) }}

  {{`{{- with secret "`}}{{ index $Global.Values.SECMAN_NAMESPACE $env }}/{{ $kvPath }}/{{ $secret.name }}{{`" -}}`}}
  {{- if not $secret.base64 }}
    {{`{{ index .Data "`}}{{ $secret.key }}{{`" }}{{"\n"}}`}}
  {{- else }}
    {{`{{ index .Data "`}}{{ $secret.key }}{{`" | base64Decode  }}{{"\n"}}`}}
  {{- end }}
  {{`{{- end }}`}}
{{- end }}
{{- end }}
# ^^^^^^^^^^^^^^^ End {{ $value.mountName }} ^^^^^^^^^^^^^^^^^^
{{- end }}
{{- end }}
{{- end -}}