apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.PROJECT_NAME }}
  labels:
    app: {{ .Values.PROJECT_NAME }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.PROJECT_NAME }}-pod
  template:
    metadata:
      labels:
        app: {{ .Values.PROJECT_NAME }}-pod
    spec:
      {{ include "resources.securityContext" . | nindent 6 }}
      {{ include "resources.priority"        . | nindent 6 }}
      containers:
# ========== IMAGE =============
      - name: {{ .Values.IMAGE.NAME }}
        image: {{ .Values.IMAGE.SOURCE }}:{{ .Values.IMAGE.VER }}
        {{- include "resources.command"      . | nindent 8 }}
        {{- include "resources.args"         . | nindent 8 }}
        {{- include "resources.envs"         . | nindent 8 }}
        {{- include "resources.limits"       . | nindent 8 }}
        {{- include "resources.ports"        . | nindent 8 }}
        {{- include "resources.healthcheck"  . | nindent 8 }}
        {{- include "resources.volumeMounts" . | nindent 8 }}
        {{- include "resources.volumes"      . | nindent 6 }}