{{- define "resources.hpa" -}}
{{- if $.Values.HPA }}
{{- $splitNamespace := splitList "-" $.Release.Namespace }} 
{{- $filteredNamespace :=  without $splitNamespace "prod" "regress" "ift" "ift1" "ift2" "dev" "lt" "lt1" "lt2" "psi" "prom" "ns" }} 
{{- $editedNamespace := join "-" $filteredNamespace | lower  }}
{{- $checksLead := dict }}{{- range $container := $.Values.CONTAINERS }}{{- if $container.lead }}{{ $_ := set $checksLead "lead" $container.presetLabel }}{{- end }}{{- end }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ index $checksLead "lead" }}-{{ $.Values.NAME }}-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ index $checksLead "lead" }}-{{ $.Values.NAME }}-{{ $editedNamespace }}-deploy
  minReplicas: {{ $.Values.HPA.MINREPL }}
  maxReplicas: {{ $.Values.HPA.MAXREPL }}
  metrics:
  {{- if $.Values.HPA.TYPE.CPU }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.HPA.TYPE.CPU }}
  {{- end }}
  {{- if $.Values.HPA.TYPE.RAM }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $.Values.HPA.TYPE.RAM }}
  {{- end }}
{{- end }}
---
{{- end -}}