{{- $splitNamespace := splitList "-" $.Release.Namespace }} 
{{- $filteredNamespace :=  without $splitNamespace "prod" "regress" "ift" "ift1" "ift2" "dev" "lt" "lt1" "lt2" "psi" "prom" "ns" }} 
{{- $editedNamespace := join "-" $filteredNamespace | lower  }}
kind: Service
apiVersion: v1
metadata:
  name: {{ ( index (index $.Values.CONTAINERS 0) "presetLabel" ) }}-{{ $.Values.NAME }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name     : {{ index $checksLead "lead" }}-{{ $.Values.NAME }}
    app.kubernetes.io/part-of  : {{ index $checksLead "lead" }}-{{ $.Values.NAME }}-{{ $editedNamespace }}
    app.kubernetes.io/component: app
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
  - IPv6
  - IPv4
  selector:
    app: {{ ( index (index $.Values.CONTAINERS 0) "presetLabel" ) }}-{{ $.Values.NAME }}-{{ $editedNamespace }}-pod
  {{- if $.Values.DIRECT_CONNECTION }}
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
    {{- range $.Values.EXTERNAL_IP}}
    - {{ . }}
    {{- end }}
  {{- end }}
  ports:
{{- range $listIndex , $array := (list 
  (index $.Values.PORTS (printf "default_%s" (upper ( index (index $.Values.CONTAINERS 0) "presetLabel" )))) 
  (index $.Values.PORTS (upper ( index (index $.Values.CONTAINERS 0) "presetLabel" )))) 
}}
  {{- range $index, $value := . }}
  - name: {{ $value.protocol | lower }}-{{ $value.name }}
    port: {{ $value.port }}
    protocol: {{ $value.protocol | upper }}
    targetPort: {{ $value.port }}
  {{- end }}
  {{- end }}
  selector:
    app: {{ ( index (index $.Values.CONTAINERS 0) "presetLabel" ) }}-{{ $.Values.NAME }}-{{ $editedNamespace }}-pod