{{- define "deployment.ports" -}}
{{- $Global := .Global }}
# --== Lib deploy ports ==--
{{- if gt (len (concat 
  (default (list) (index $Global.Values.PORTS (printf "default_%s" (upper .presetLabel)))) 
  (default (list) (index $Global.Values.PORTS (upper .presetLabel)))
)) 0 }}
ports:
{{- range $index, $value := (concat 
  (default (list) (index $Global.Values.PORTS (printf "default_%s" (upper .presetLabel)))) 
  (default (list) (index $Global.Values.PORTS (upper .presetLabel)))
)}}
  - name: tcp-{{ $value }}
    containerPort: {{ $value }}
    protocol: TCP
{{- end }}
{{- end }}
{{- end -}}
