{{- define "resources.priority" -}}
{{- if $.Values.PRIORITY }}
{{- $checksLead := dict }}{{- range $container := $.Values.CONTAINERS }}{{- if $container.lead }}{{ $_ := set $checksLead "lead" $container.presetLabel }}{{- end }}{{- end }}
# ========== PRIORITY ===========
priorityClassName: {{ index $checksLead "lead" }}-{{ $.Values.NAME }}-pc
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      {{- if  $.Values.PRIORITY.STRICT }}
        - matchExpressions:
            {{- range $.Values.PRIORITY.NODE_SELECTOR }}
            - key: {{ .label }}
              operator: In
              values:
                {{- range .value }}
                - "{{ . }}"
                {{- end }}
            {{- end }}
      {{- else }}
            {{- range $.Values.PRIORITY.NODE_SELECTOR }}
        - matchExpressions:
            - key: {{ .label }}
              operator: In
              values:
                {{- range .value }}
                - "{{ . }}"
                {{- end }}
            {{- end }}
      {{- end }}
{{- end }}
{{- end -}}