{{- define "deployment.resources" -}}
{{- $Global := .Global }}
# --== Lib deploy resources ==--
{{- $splitResource := splitList "/" (tpl (print "{{ $.Values.RESOURCE_" (.Global.Values.NAME | upper | replace "-" "_") "_" (.presetLabel | upper | replace "-" "_") " }}") $Global) }} 
resources:
  limits:
    cpu:    {{ (index $splitResource 0) }}
    memory: {{ (index $splitResource 1) }}
  requests:
    cpu:    {{ (index $splitResource 2) }}
    memory: {{ (index $splitResource 3) }}
{{- end -}}