{{- define "deployment.volumeMounts" -}}
{{- $Global := .Global }}
# --== Lib deploy volumeMounts ==--
volumeMounts:
{{- range $index, $value := .volumeMounts }}
{{- if $value.hostPath}}
# == VolumeMount {{ .name }} hostPath ==
- name: {{ $value.name }}-volume
  mountPath: {{ $value.mountPath }}
  {{- if $value.readOnly }}
  readOnly: {{ $value.readOnly }}
  {{- end }}
{{- else if $value.secretName }}
# == VolumeMount {{ .name }} secret ==
- name: {{ $value.name }}-volume
  mountPath: {{ $value.mountPath }}
  subPath: {{ $value.subPath }}
  {{- if $value.readOnly }}
  readOnly: {{ $value.readOnly }}
  {{- end }}
{{- else if .aws_efs_id }}
- name: {{ .name }}-volume
  mountPath: {{ .mountPath }}
  readOnly: {{ .readOnly }}
{{- else if $value.fieldRef }}
# == VolumeMount {{ $value.name }} fieldRef ==
- name: {{ $value.name }}-volume
  mountPath: {{ $value.mountPath }}
{{- else if $value.serviceAccountToken }}
# == VolumeMount {{ $value.name }} serviceAccountToken ==
- name: {{ $value.name }}-volume
  readOnly: true
  mountPath: {{ $value.mountPath }}
{{- else if $value.configMapName }}
# == VolumeMount {{ $value.name }} configMap ==
- name: {{ $value.name }}-volume
  mountPath: {{ $value.mountPath }}/{{ $value.subPath }}
  subPath: {{ $value.subPath }}
  {{- if $value.readOnly }}
  readOnly: {{ $value.readOnly }}
  {{- end }}
{{- else if eq $value.emptyDir "regular" }}
# == VolumeMount {{ $value.name }} emptyDir ==
- name: {{ $value.name }}-volume
  mountPath: {{ $value.mountPath }}
  {{- if $value.readOnly }}
  readOnly: {{ $value.readOnly }}
  {{- end }}
{{- else if eq $value.emptyDir "memory" }}
# == VolumeMount {{ $value.name }} emptyDir memory ==
- name: {{ $value.name }}-volume
  mountPath: {{ $value.mountPath }}
  {{- if $value.readOnly }}
  readOnly: {{ $value.readOnly }}
  {{- end }}
{{- end }}
{{- end }}
{{- end -}}