{{- define "deployment.body" -}}
{{- $jiraTeam := regexFind "[a-zA-Z]+" $.Values.JIRA_ID | lower }}
{{- $splitNamespace := splitList "-" $.Release.Namespace | rest  }} 
{{- $filteredNamespace :=  without $splitNamespace "prod" "regress" "ift" "ift1" "ift2" "dev" "lt" "lt1" "lt2" "psi" "prom" }} 
{{- $editedNamespace := join "-" $filteredNamespace | lower  }}
{{- range $index, $value := $.Values.CONTAINERS }}
  {{- if not (has $.Values.ENVIRONMENT $value.excludeStands) }}
# --== Подключение {{ $value.presetLabel }} контейнера ==--
{{- /* ======================== Конфигурация образа =========================== */}}
- name: {{ $value.presetLabel | lower }}-{{ $.Values.NAME }}-{{ $editedNamespace }}
  image: {{ index $.Values.IMAGE_PATHS $.Values.ENVIRONMENT }}/{{ index $.Values.IMAGES (upper $value.presetLabel) }}
  imagePullPolicy: Always
{{- /* ===================== Аргументы и команды  ============================= */}}
  {{- include "deployment.commands" (dict "Global" $ "presetLabel" $value.presetLabel ) | nindent 2 }}
  {{- include "deployment.args"     (dict "Global" $ "presetLabel" $value.presetLabel ) | nindent 2 }}
{{- /* ===================== Перменные окружения ============================== */}}
  {{- include "deployment.environments" (dict "Global" $ "presetLabel" $value.presetLabel )    | nindent 2 }}
{{- /* ======================== HEALTHCHECK =================================== */}}
  {{- include "deployment.probes"    (dict "Global" $ "presetLabel" $value.presetLabel )       | nindent 2 }}
  {{- include "deployment.lifecycle" (dict "Global" $ "presetLabel" $value.presetLabel )       | nindent 2 }}
{{- /* =================== Политики безопасности ============================== */}}
  {{- include "deployment.securityContext" (dict "Global" $ "presetLabel" $value.presetLabel ) | nindent 2 }}  
{{- /* ========================= Порты ======================================== */}}        
  {{- include "deployment.ports" (dict "Global" $ "presetLabel" $value.presetLabel )           | nindent 2 }}  
{{- /* ===================== Немного хардкода ================================= */}}
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
{{- /* ======================== Ресурсы ======================================= */}}
  {{- include "deployment.resources" (dict "Global" $ "presetLabel" $value.presetLabel ) | nindent 2 }}
{{- /* =================== Монтироание дирикторий ============================= */}}
  volumeMounts:
  {{- include "deployment.volumeMounts" (dict "Global" $ "presetLabel" $value.presetLabel ) | nindent 2 }}
  {{- end }}
{{- end }}
{{- end -}}