{{- define "configMaps.DCM" -}}
{{- $Global := .Global }}
{{- $splitNamespace := splitList "-" $Global.Release.Namespace   }} 
{{- $filteredNamespace :=  without $splitNamespace "prod" "regress" "ift" "ift1" "ift2" "dev" "lt" "lt1" "lt2" "psi" "prom" "ns" }} 
{{- $editedNamespace := join "-" $filteredNamespace | lower  }}
{{- $checksLead := dict }}{{- range $container := $Global.Values.CONTAINERS }}{{- if $container.lead }}{{ $_ := set $checksLead "lead" $container.presetLabel }}{{- end }}{{- end }}
{{- if or 
  (index $Global.Values.DCM (printf "default_%s" (upper .presetLabel))) 
  (index $Global.Values.DCM (upper .presetLabel)) 
-}}
# --== Lib deploy Dynamic ConfigMap ==--
  {{- range $listIndex , $array := (list 
    (index $Global.Values.DCM (printf "default_%s" (upper .presetLabel))) 
    (index $Global.Values.DCM (upper .presetLabel))
  ) -}}
  {{- range $owner_cm, $cms := . }}
    {{- if (or (not $Global.Values.DCM_SELECTOR) (has $cms.configMapName $Global.Values.DCM_SELECTOR)) }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ index $checksLead "lead" }}-{{ $Global.Values.NAME }}-{{ $cms.configMapName }}
  namespace: {{ $Global.Release.Namespace }}
  labels:
    app.kubernetes.io/part-of  : {{ $Global.Release.Namespace }}
    app.kubernetes.io/component: app
data:
  {{ $cms.subPath }}: |-
      {{- $file_content := dict }}
      {{- range $key, $val := $cms.content }}
        {{- if eq $key 0 }}
          {{- $_ := set $file_content "custom" $val.data }}
        {{- else }}
          {{- if $val.data }}{{- if eq (typeOf $val.data) "map[string]interface {}" }}{{- $_ := set $file_content "data" (ternary (index $val.data $Global.Values.ENVIRONMENT) "" (has $Global.Values.ENVIRONMENT (keys $val.data))) }}{{- else }}{{- $_ := set $file_content "data" $val.data}}{{- end }}{{- end }}
          {{- if $val.data_nl }}{{- if eq (typeOf $val.data_nl) "map[string]interface {}" }}{{- $_ := set $file_content "data" (ternary (index $val.data_nl $Global.Values.ENVIRONMENT) "" (has $Global.Values.ENVIRONMENT (keys $val.data_nl))) }}{{- else }}{{- $_ := set $file_content "data" $val.data_nl}}{{- end }}{{- end }}
          {{- if $val.data }}{{- $_ := set $file_content "custom" (print (index $file_content "custom") (index $file_content "data")) }}{{- else }}{{- $_ := set $file_content "custom" (print (println (index $file_content "custom")) (index $file_content "data")) }}{{- end }}
        {{- end }}
      {{- end }}
      {{- tpl (index $file_content "custom") $Global | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end -}}
      