{{- define "resources.hpa" -}}
{{- if $.Values.HPA }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Values.PROJECT_NAME }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.PROJECT_NAME }}-deploy
  minReplicas: {{ $.Values.HPA.MINREPL }}
  maxReplicas: {{ $.Values.HPA.MAXREPL }}
  metrics:
  {{- if $.Values.HPA.TYPE.CPU }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.HPA.TYPE.CPU }}
  {{- end }}
  {{- if $.Values.HPA.TYPE.RAM }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $.Values.HPA.TYPE.RAM }}
  {{- end }}
{{- end }}
{{- end -}}