{{- define "resources.priorityClass" -}}
{{- if $.Values.PRIORITY }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.PROJECT_NAME }}-pc
value: {{ $.Values.PRIORITY.VALUE }}
globalDefault: false
---
{{- end }}
{{- end -}}