apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.PROJECT_NAME }}-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.PROJECT_NAME }}-pod
  template:
    metadata:
      labels:
        app: {{ .Values.PROJECT_NAME }}-pod
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
# ========== IMAGE =============
      - name: {{ .Values.IMAGE.NAME }}
        image: {{ .Values.IMAGE.SOURCE }}:{{ .Values.IMAGE.VER }}
          {{- include "resources.limits"       . | nindent 8 }}
          {{- include "resources.ports"        . | nindent 8 }}
          {{- include "resources.healthcheck"  . | nindent 8 }}
          {{- include "resources.volumeMounts" . | nindent 8 }}
          {{- include "resources.volumes"      . | nindent 6 }}